<?php

namespace Workbench\Database\Factories;

use Orchestra\Testbench\Factories\UserFactory as OrchestraUserFactory;
use Workbench\App\Models\User;

/**
 * @template TModel of \Workbench\App\Models\User
 */
class UserFactory extends OrchestraUserFactory {
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName() {
        return User::class;
    }
}
