name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          npm i -g conventional-changelog-cli@^3.0.0
          conventional-changelog -p angular -o CHANGELOG.md -r 2
          tail -n +2 CHANGELOG.md > CHANGELOG #remove first line
          sed -i -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}' CHANGELOG #trim empty lines

      - name: Release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: CHANGELOG
        env:
          GITHUB_TOKEN: ${{ github.token }}
